# Generated by Django 4.2.4 on 2023-10-04 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulenti', '0001_initial'),
        ('utils', '0004_codiciiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='GruppoListino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_gruppo', models.CharField(max_length=30)),
                ('descrizione_gruppo', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Gruppo Listino',
                'verbose_name_plural': 'Gruppi Listino',
            },
        ),
        migrations.CreateModel(
            name='Programmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_programma', models.CharField(max_length=50)),
                ('descrizione_programma', models.CharField(max_length=250)),
                ('descrizione_in_fattura', models.CharField(max_length=250)),
                ('durata_programma', models.IntegerField(blank=True, null=True)),
                ('importo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fasce_kg', models.CharField(blank=True, max_length=5, null=True)),
                ('validita_per_bilanciamento', models.BooleanField(default=False)),
                ('programma_attivo', models.BooleanField(default=False)),
                ('programma_intero', models.BooleanField(default=False)),
                ('programma_amministratore', models.BooleanField(default=False)),
                ('data_creazione', models.DateField(auto_now_add=True)),
                ('data_ultima_modifica', models.DateField(auto_now=True)),
                ('codiceiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.codiciiva')),
                ('gruppo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gruppo', to='listini.gruppolistino')),
                ('listino_dedicato', models.ManyToManyField(blank=True, related_name='listino_dedicato', to='consulenti.struttura')),
            ],
            options={
                'verbose_name': 'Programma',
                'verbose_name_plural': 'Programma',
            },
        ),
    ]
