# Generated by Django 4.2.4 on 2023-10-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruppolistino',
            name='myw8fa_visibilita',
            field=models.BooleanField(default=False),
        ),
    ]
