# Generated by Django 4.2.4 on 2023-08-22 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('prezzo', models.CharField(max_length=10)),
                ('premio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RegimiFiscali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_regime', models.CharField(max_length=20)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Regime Fiscale',
                'verbose_name_plural': 'Regimi Fiscali',
            },
        ),
        migrations.CreateModel(
            name='AnagraficaUtente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('luogo_di_nascita', models.CharField(max_length=50)),
                ('provincia_di_nascita', models.CharField(max_length=2)),
                ('data_nascita', models.DateField()),
                ('codice_fiscale', models.CharField(max_length=16)),
                ('numero_civico', models.CharField(max_length=5, null=True)),
                ('citta_di_residenza', models.CharField(max_length=25)),
                ('provincia_di_residenza', models.CharField(max_length=2)),
                ('regione_residenza', models.CharField(max_length=30)),
                ('stato_residenza', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('cellulare', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=150)),
                ('banca_appoggio', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True, null=True)),
                ('corner', models.BooleanField(choices=[(True, 'Corner'), (False, 'Centro Autorizzato')], default=False)),
                ('titolare_di', models.IntegerField(choices=[(1, 'Centro Benessere/Estetico'), (2, 'Palestra/Personal Trainer'), (3, 'Studio Specialista')], default=1)),
                ('denominato', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=10)),
                ('comune', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=10)),
                ('PICF', models.CharField(max_length=50)),
                ('pagamento', models.BooleanField(choices=[(True, 'Unica Soluzione'), (False, 'Rateizzato')], default=False)),
                ('ruolo_altra_azienda', models.BooleanField(default=False)),
                ('imponibile_provvigionale', models.FloatField(blank=True, null=True)),
                ('imponibile_provvigionale_parole', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('partita_iva_ateco', models.BooleanField(default=False)),
                ('partita_iva', models.CharField(blank=True, default='', max_length=11, null=True)),
                ('gestione_separata_inps', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_modifica', models.DateTimeField(auto_now_add=True)),
                ('livello_consulente', models.IntegerField(choices=[(0, '-------'), (1, 'Manager'), (2, 'Top Manager'), (3, 'Silver Manager'), (4, 'Gold Manager'), (5, 'Platinum Manager')], default=0)),
                ('data_tesserino', models.DateField(blank=True, null=True)),
                ('numero_tesserino', models.IntegerField(blank=True, null=True)),
                ('numero_IVD', models.IntegerField(blank=True, null=True)),
                ('affiliatore', models.ForeignKey(blank=True, null=True, on_delete=models.SET('senza superiore'), related_name='affiliati_anagrafica', to='utente.anagraficautente')),
                ('formula_scelta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utente.formulacentro')),
                ('id_superiore', models.ForeignKey(blank=True, null=True, on_delete=models.SET('senza superiore'), related_name='superiore_anagrafica', to='utente.anagraficautente')),
                ('regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utente.regimifiscali')),
                ('seguito', models.ForeignKey(blank=True, null=True, on_delete=models.SET('senza superiore'), related_name='seguito_anagrafica', to='utente.anagraficautente')),
                ('utente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Utente',
                'verbose_name_plural': 'Utenti',
            },
        ),
    ]
